from .dance_poser import NODE_CLASS_MAPPINGS as DANCE_NODES, NODE_DISPLAY_NAME_MAPPINGS as DANCE_DISPLAY
from .pose_tensor_extract import NODE_CLASS_MAPPINGS as EXTRACT_NODES, NODE_DISPLAY_NAME_MAPPINGS as EXTRACT_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(DANCE_NODES)
NODE_CLASS_MAPPINGS.update(EXTRACT_NODES)

NODE_DISPLAY_NAME_MAPPINGS.update(DANCE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(EXTRACT_DISPLAY)
